server:
  port: 7990

telegram:
  bot:
    name: YOUR_BOT_NAME
    token: YOUR_BOT_TOKEN

spring:
  datasource:
    url: jdbc:sqlite:./time_princess.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin

  jpa:
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
